import { NextResponse } from 'next/server';
import { getServerSession } from "next-auth";
import { authOptions } from "@/lib/auth";
import { prisma } from "@/lib/prisma";
import JSZip from 'jszip';
import { validateRequest, ExportSchema, apiError } from '@/lib/validators';
import { verifyProjectOwnership } from '@/lib/security';

export async function GET(req: Request) {
  try {
    const session = await getServerSession(authOptions);
    if (!session?.user) {
      return new NextResponse("Unauthorized", { status: 401 });
    }

    const { searchParams } = new URL(req.url);
    const validation = validateRequest(ExportSchema, {
      projectId: searchParams.get('projectId') || '',
      format: searchParams.get('format') || 'zip',
    });
    if (!validation.success) {
      return NextResponse.json(apiError(`Validation failed: ${validation.errors?.join(', ')}`), { status: 400 });
    }
    const { projectId } = validation.data!;

    const isAuthorized = await verifyProjectOwnership(projectId, session);
    if (!isAuthorized) return new NextResponse("Forbidden", { status: 403 });

    const project = await prisma.project.findUnique({
      where: { id: projectId }
    });

    if (!project) {
      return new NextResponse("Project not found", { status: 404 });
    }

    // Fetch all code files
    const files = await prisma.codeFile.findMany({
      where: { projectId }
    });

    if (files.length === 0) {
      return new NextResponse("No generated code files found for this project.", { status: 404 });
    }

    // Create a new JSZip instance
    const zip = new JSZip();

    // Populate the zip with files from the Virtual File System
    files.forEach((file: any) => {
      // file.path usually looks like 'src/components/Button.tsx'
      zip.file(file.path, file.content);
    });

    // We can also generate a generic README
    const readmeContent = `# ${project.name}
This project was automatically generated by the Bhagvat Gita Autonomous Software Factory.

## Overview
${project.description || 'No description provided.'}

## Project Execution
This codebase was mapped by an AI Agent inside the Execution Studio and verified by a local Quality Swarm.
`;
    zip.file("README.md", readmeContent);

    // Generate the zip binary stream
    const zipBuffer = await zip.generateAsync({ type: "uint8array", compression: "DEFLATE" });

    // Return the response as an attachment
    const filename = `${project.name.replace(/[^a-z0-9]/gi, '_').toLowerCase()}_repository.zip`;

    return new NextResponse(zipBuffer as any, {
      status: 200,
      headers: {
        'Content-Type': 'application/zip',
        'Content-Disposition': `attachment; filename="${filename}"`
      }
    });

  } catch (error: any) {
    console.error("Export Error:", error);
    return new NextResponse(`Export Failed: ${error.message}`, { status: 500 });
  }
}
