'use client';

import { useState, useEffect } from 'react';
import { useParams } from 'next/navigation';
import { LayoutPanelLeft, Plus, GripVertical, CheckCircle2, Clock, AlertCircle } from 'lucide-react';

interface Task {
  id: string;
  title: string;
  description: string | null;
  status: string;
  priority: string;
  tokens: number;
}

const COLUMNS = [
  { id: 'TODO', title: 'To Do', color: 'bg-gray-500' },
  { id: 'IN_PROGRESS', title: 'In Progress', color: 'bg-yellow-500' },
  { id: 'DONE', title: 'Done', color: 'bg-green-500' },
];

export default function KanbanBoard() {
  const [projectId, setProjectId] = useState<string | null>(null);

  useEffect(() => {
    setProjectId(localStorage.getItem('activeProjectId'));
  }, []);
  
  const [tasks, setTasks] = useState<Task[]>([]);
  const [loading, setLoading] = useState(true);

  const fetchTasks = async () => {
    if (!projectId) return;
    const res = await fetch(`/api/tasks?projectId=${projectId}`);
    const data = await res.json();
    if (data.success) {
      setTasks(data.tasks);
    }
    setLoading(false);
  };

  useEffect(() => {
    if (projectId) {
      fetchTasks();
    }
  }, [projectId]);

  const moveTask = async (taskId: string, newStatus: string) => {
    // Optimistic UI update
    setTasks(prev => prev.map(t => t.id === taskId ? { ...t, status: newStatus } : t));
    
    // API update
    await fetch('/api/tasks', {
      method: 'PATCH',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ id: taskId, status: newStatus })
    });
  };

  if (loading) {
    return <div className="p-8 text-white">Loading board...</div>;
  }

  return (
    <div className="h-full w-full flex flex-col p-8 animate-in fade-in slide-in-from-bottom-4 duration-500">
      
      <div className="mb-8 flex justify-between items-end">
        <div>
          <h1 className="text-3xl font-extrabold text-white tracking-tight flex items-center gap-3">
            <LayoutPanelLeft className="w-8 h-8 text-[#5b5fd8]" />
            Jira-Style Execution Board
          </h1>
          <p className="text-[#8b9bb4] mt-2 text-sm">
            Track tasks, time estimates, and token utilization generated by the Auto-Intel Pipeline.
          </p>
        </div>
        <button className="bg-white/10 hover:bg-white/20 text-white px-4 py-2 rounded-lg font-bold flex items-center gap-2 transition-colors text-sm">
          <Plus className="w-4 h-4" /> Add Task Manually
        </button>
      </div>

      <div className="flex-1 flex gap-6 overflow-x-auto pb-4 custom-scrollbar">
        {COLUMNS.map(col => (
          <div key={col.id} className="w-[350px] flex-shrink-0 flex flex-col bg-[#0b0e14] border border-[#1e2532] rounded-2xl overflow-hidden">
            
            <div className="p-4 border-b border-[#1e2532] bg-[#1a1b3b]/30 flex items-center justify-between">
              <h2 className="text-sm font-bold text-white flex items-center gap-2">
                <div className={`w-2.5 h-2.5 rounded-full ${col.color}`} />
                {col.title}
              </h2>
              <span className="text-xs font-mono text-[#586c8f] bg-black/50 px-2 py-0.5 rounded border border-[#1e2532]">
                {tasks.filter(t => t.status === col.id).length}
              </span>
            </div>

            <div className="flex-1 p-3 space-y-3 overflow-y-auto">
              {tasks.filter(t => t.status === col.id).map(task => (
                <div 
                  key={task.id} 
                  className="bg-[#1a1b3b]/50 border border-[#1e2532] hover:border-[#5b5fd8]/50 p-4 rounded-xl cursor-grab active:cursor-grabbing transition-all group"
                >
                  <div className="flex items-start justify-between mb-2">
                    <span className="text-xs font-bold px-2 py-0.5 rounded uppercase tracking-wider bg-white/5 text-gray-400">
                      {task.priority}
                    </span>
                    <GripVertical className="w-4 h-4 text-[#586c8f] opacity-0 group-hover:opacity-100 transition-opacity" />
                  </div>
                  
                  <h3 className="text-sm font-bold text-white mb-1">{task.title}</h3>
                  {task.description && (
                    <p className="text-xs text-[#8b9bb4] line-clamp-2 mb-3">{task.description}</p>
                  )}
                  
                  <div className="flex items-center justify-between pt-3 border-t border-[#1e2532]/50 mt-2">
                    <div className="flex items-center gap-3 text-[10px] font-mono text-[#586c8f]">
                      <span className="flex items-center gap-1" title="Estimated Tokens">
                        <Clock className="w-3 h-3" /> {task.tokens} Tokens
                      </span>
                    </div>
                    
                    {/* Quick Move Buttons */}
                    <div className="flex items-center gap-1 opacity-0 group-hover:opacity-100 transition-opacity">
                      {col.id !== 'TODO' && (
                        <button onClick={() => moveTask(task.id, 'TODO')} className="p-1 hover:bg-white/10 rounded text-gray-400" title="Move to To Do">
                          <AlertCircle className="w-3 h-3" />
                        </button>
                      )}
                      {col.id !== 'IN_PROGRESS' && (
                        <button onClick={() => moveTask(task.id, 'IN_PROGRESS')} className="p-1 hover:bg-white/10 rounded text-yellow-400" title="Move to In Progress">
                          <Clock className="w-3 h-3" />
                        </button>
                      )}
                      {col.id !== 'DONE' && (
                        <button onClick={() => moveTask(task.id, 'DONE')} className="p-1 hover:bg-white/10 rounded text-green-400" title="Move to Done">
                          <CheckCircle2 className="w-3 h-3" />
                        </button>
                      )}
                    </div>
                  </div>
                </div>
              ))}
              
              {tasks.filter(t => t.status === col.id).length === 0 && (
                <div className="h-24 flex items-center justify-center text-xs text-[#586c8f] border-2 border-dashed border-[#1e2532] rounded-xl">
                  Drop tasks here
                </div>
              )}
            </div>

          </div>
        ))}
      </div>

    </div>
  );
}
