'use client';

import { useState, useEffect } from 'react';
import {
  Layers, Sparkles, Loader2, FolderOpen, Copy, Check, Download,
  Code2, Globe, Palette, Wind, Heart, Terminal, GitBranch, MessageSquare, Bot, Gem
} from 'lucide-react';

const platforms = [
  { id: 'cursor', name: 'Cursor', icon: Code2, color: 'text-blue-400', bgColor: 'bg-blue-500/10 border-blue-500/30', desc: 'AI Code Editor' },
  { id: 'bolt', name: 'Bolt', icon: Globe, color: 'text-yellow-400', bgColor: 'bg-yellow-500/10 border-yellow-500/30', desc: 'StackBlitz AI' },
  { id: 'v0', name: 'V0', icon: Palette, color: 'text-white', bgColor: 'bg-white/10 border-white/30', desc: 'Vercel UI Gen' },
  { id: 'windsurf', name: 'Windsurf', icon: Wind, color: 'text-teal-400', bgColor: 'bg-teal-500/10 border-teal-500/30', desc: 'Codeium IDE' },
  { id: 'lovable', name: 'Lovable', icon: Heart, color: 'text-pink-400', bgColor: 'bg-pink-500/10 border-pink-500/30', desc: 'Full-Stack AI' },
  { id: 'replit', name: 'Replit', icon: Terminal, color: 'text-orange-400', bgColor: 'bg-orange-500/10 border-orange-500/30', desc: 'Cloud IDE AI' },
  { id: 'copilot', name: 'GitHub Copilot', icon: GitBranch, color: 'text-green-400', bgColor: 'bg-green-500/10 border-green-500/30', desc: 'Code Completion' },
  { id: 'claude', name: 'Claude', icon: MessageSquare, color: 'text-amber-400', bgColor: 'bg-amber-500/10 border-amber-500/30', desc: 'Anthropic AI' },
  { id: 'chatgpt', name: 'ChatGPT', icon: Bot, color: 'text-emerald-400', bgColor: 'bg-emerald-500/10 border-emerald-500/30', desc: 'OpenAI GPT' },
  { id: 'gemini', name: 'Gemini 3.1 Pro High', icon: Gem, color: 'text-indigo-400', bgColor: 'bg-indigo-500/10 border-indigo-500/30', desc: 'Google AI' },
];

const phases = [
  { id: 1, name: 'KB & UI Foundation', key: 'kb-ui' },
  { id: 2, name: 'Authentication & Auth', key: 'auth' },
  { id: 3, name: 'Frontend Components', key: 'frontend' },
  { id: 4, name: 'Data Models & Schema', key: 'data-models' },
  { id: 5, name: 'API Development', key: 'api' },
  { id: 6, name: 'External API Integration', key: 'external-apis' },
  { id: 7, name: 'Data Sync & Pipelines', key: 'data-sync' },
  { id: 8, name: 'Admin & Dashboard', key: 'admin' },
  { id: 9, name: 'Testing & QA', key: 'testing' },
  { id: 10, name: 'Deploy & DevOps', key: 'deploy' },
];

const platformTemplates: Record<string, string> = {
  cursor: `# Cursor Rules File (.cursorrules)
# Generated by Launch IQ

## Project Context
{{PROJECT_CONTEXT}}

## Phase: {{PHASE_NAME}} (Phase {{PHASE_NUMBER}}/10)

## Instructions
You are an expert {{TECH_STACK}} developer. Follow these rules strictly:

### Architecture Rules
- Use the App Router with Server Components by default
- Client Components only when interactivity is required ('use client')
- Implement proper error boundaries and loading states
- Use TypeScript strict mode with no 'any' types

### Code Standards
{{PHASE_INSTRUCTIONS}}

### File Structure
- Follow the established project file structure
- Group related components in feature directories
- Export types from dedicated type files

### Phase-Specific Deliverables
{{PHASE_DELIVERABLES}}`,

  bolt: `# Bolt.new Prompt
# Platform: StackBlitz WebContainer
# Generated by Launch IQ

## Project: {{PROJECT_CONTEXT}}
## Phase: {{PHASE_NAME}} ({{PHASE_NUMBER}}/10)

Build the following using the StackBlitz WebContainer environment:

### Requirements
{{PHASE_INSTRUCTIONS}}

### Technical Constraints
- Single-page deployment in WebContainer
- Use npm packages compatible with browser runtime
- Ensure all imports resolve correctly
- Include inline styles or Tailwind CSS

### Deliverables
{{PHASE_DELIVERABLES}}

### Important
- Generate COMPLETE, working code — no placeholders
- Include all necessary imports
- Handle errors gracefully with user-friendly messages`,

  v0: `// V0 by Vercel — UI Generation Prompt
// Generated by Launch IQ

// Project: {{PROJECT_CONTEXT}}
// Phase: {{PHASE_NAME}} ({{PHASE_NUMBER}}/10)

Create a React component with the following specifications:

Design System:
- Use shadcn/ui components
- Tailwind CSS for styling
- Dark theme with consistent color palette
- Responsive design (mobile-first)
- Smooth animations and transitions

Component Requirements:
{{PHASE_INSTRUCTIONS}}

Specifications:
{{PHASE_DELIVERABLES}}

Style Notes:
- Use bg-background, text-foreground for theming
- Add hover/focus states to all interactive elements
- Include proper aria labels for accessibility
- Use Lucide icons for iconography`,

  windsurf: `# Windsurf (Codeium) Rules
# Generated by Launch IQ

## Project Context
{{PROJECT_CONTEXT}}

## Active Phase: {{PHASE_NAME}} (Phase {{PHASE_NUMBER}})

## Cascade Instructions
Follow these rules when generating or editing code:

### Phase Objectives
{{PHASE_INSTRUCTIONS}}

### Code Generation Rules
1. Always use TypeScript with strict type checking
2. Implement comprehensive error handling
3. Add JSDoc comments to all exports
4. Follow existing project patterns and conventions
5. Write unit tests alongside feature code

### Deliverables for This Phase
{{PHASE_DELIVERABLES}}

### Quality Gates
- No TypeScript errors
- All exports documented
- Error boundaries in place
- Loading states implemented`,

  lovable: `# Lovable.dev Full-Stack Prompt
# Generated by Launch IQ

## Project: {{PROJECT_CONTEXT}}
## Phase: {{PHASE_NAME}} ({{PHASE_NUMBER}}/10)

Build a production-ready full-stack feature with:

### Frontend (React + Tailwind)
{{PHASE_INSTRUCTIONS}}

### Backend (Supabase)
- Define database tables with RLS policies
- Create Edge Functions for business logic
- Set up real-time subscriptions where needed

### Deliverables
{{PHASE_DELIVERABLES}}

### Design Requirements
- Modern, clean UI with dark mode support
- Responsive across all breakpoints
- Smooth page transitions and micro-interactions
- Toast notifications for all user actions`,

  replit: `# Replit Agent Prompt
# Generated by Launch IQ

## Project: {{PROJECT_CONTEXT}}
## Phase: {{PHASE_NAME}} (Phase {{PHASE_NUMBER}}/10)

### Goal
{{PHASE_INSTRUCTIONS}}

### Environment Setup
- Runtime: Node.js 20+
- Framework: Next.js 14+ with App Router
- Database: PostgreSQL via Prisma ORM
- Styling: Tailwind CSS

### Implementation Steps
{{PHASE_DELIVERABLES}}

### Replit-Specific Notes
- Use .replit configuration for run commands
- Set environment variables in Secrets tab
- Configure port forwarding for preview
- Ensure all dependencies in package.json`,

  copilot: `# GitHub Copilot Workspace Instructions
# .github/copilot-instructions.md
# Generated by Launch IQ

## Project Context
{{PROJECT_CONTEXT}}

## Current Phase: {{PHASE_NAME}} ({{PHASE_NUMBER}}/10)

## Code Generation Preferences
- Language: TypeScript (strict mode)
- Framework: Next.js 14+ App Router
- Styling: Tailwind CSS
- State Management: Zustand
- Testing: Vitest + Playwright

## Phase Instructions
{{PHASE_INSTRUCTIONS}}

## Deliverables
{{PHASE_DELIVERABLES}}

## Conventions
- Use named exports over default exports
- Prefer async/await over .then() chains
- Use zod for runtime validation
- Implement proper error types
- Add comprehensive JSDoc comments`,

  claude: `# Claude Project Prompt
# Generated by Launch IQ

<context>
Project: {{PROJECT_CONTEXT}}
Phase: {{PHASE_NAME}} ({{PHASE_NUMBER}}/10)
</context>

<instructions>
You are a senior full-stack developer building a production application. Focus exclusively on Phase {{PHASE_NUMBER}}: {{PHASE_NAME}}.

## Requirements
{{PHASE_INSTRUCTIONS}}

## Deliverables
{{PHASE_DELIVERABLES}}

## Quality Standards
- TypeScript strict mode, zero 'any' types
- Comprehensive error handling with typed errors
- Full test coverage for critical paths
- Accessible UI (WCAG 2.1 AA)
- Performance budgets: LCP < 2.5s, FID < 100ms

## Output Format
Provide complete, production-ready code files. Include file paths as comments. No placeholder comments — implement everything fully.
</instructions>`,

  chatgpt: `# ChatGPT Development Prompt
# Generated by Launch IQ

## Role
You are a senior software architect and full-stack developer. You write production-grade, clean, well-documented code.

## Project
{{PROJECT_CONTEXT}}

## Current Phase: {{PHASE_NAME}} (Phase {{PHASE_NUMBER}} of 10)

## Task
{{PHASE_INSTRUCTIONS}}

## Expected Deliverables
{{PHASE_DELIVERABLES}}

## Rules
1. Write COMPLETE code — no shortcuts, no "// ... rest of implementation"
2. Use TypeScript with proper types for everything
3. Follow SOLID principles and clean architecture
4. Include error handling, loading states, and edge cases
5. Add inline comments explaining complex logic
6. Structure output with clear file paths

## Tech Stack
Next.js 14+, TypeScript, Tailwind CSS, Prisma, Zustand, Zod`,

  gemini: `# Google Gemini 3.1 Pro High — Development Prompt
# Generated by Launch IQ

## System Instructions
You are an elite full-stack software engineer working on a production application. Use your extended thinking capabilities for complex architectural decisions. Provide complete, deployable code.

## Project Context
{{PROJECT_CONTEXT}}

## Phase: {{PHASE_NAME}} ({{PHASE_NUMBER}}/10)

## Objectives
{{PHASE_INSTRUCTIONS}}

## Deliverables
{{PHASE_DELIVERABLES}}

## Technical Standards
- TypeScript strict mode with comprehensive type definitions
- Next.js 14+ App Router with RSC (React Server Components)
- Tailwind CSS with design tokens
- Prisma ORM with migration files
- Zod validation schemas
- Zustand for client-side state
- React Query for server state

## Quality Requirements
- Zero TypeScript errors
- Complete error boundaries
- Optimistic updates where applicable
- Streaming responses for AI features
- Edge-runtime compatible where possible

## Output Format
Return complete files with paths. Use markdown code blocks with language identifiers. Implement ALL functionality — no placeholders or TODOs.`,
};

export default function PromptCompilerPage() {
  const [projectId, setProjectId] = useState<string | null>(null);
  const [projects, setProjects] = useState<any[]>([]);
  const [selectedPlatform, setSelectedPlatform] = useState('cursor');
  const [selectedPhases, setSelectedPhases] = useState<number[]>([1]);
  const [output, setOutput] = useState('');
  const [isGenerating, setIsGenerating] = useState(false);
  const [copied, setCopied] = useState(false);

  useEffect(() => {
    const id = localStorage.getItem('activeProjectId');
    setProjectId(id);
    fetch('/api/projects').then(r => r.json()).then(d => { if (d.success) setProjects(d.projects); }).catch(() => {});
  }, []);

  const togglePhase = (phaseId: number) => {
    setSelectedPhases(prev => prev.includes(phaseId) ? prev.filter(p => p !== phaseId) : [...prev, phaseId].sort((a, b) => a - b));
  };

  const handleCopy = async () => {
    await navigator.clipboard.writeText(output);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleExportZip = async () => {
    const allPrompts: string[] = [];
    for (const p of platforms) {
      const template = platformTemplates[p.id] || '';
      const phaseNames = selectedPhases.map(id => phases.find(ph => ph.id === id)?.name || '').join(', ');
      const compiled = template
        .replace(/\{\{PROJECT_CONTEXT\}\}/g, projectId || 'Software Project')
        .replace(/\{\{PHASE_NAME\}\}/g, phaseNames)
        .replace(/\{\{PHASE_NUMBER\}\}/g, selectedPhases.join(', '))
        .replace(/\{\{TECH_STACK\}\}/g, 'Next.js + TypeScript + Tailwind')
        .replace(/\{\{PHASE_INSTRUCTIONS\}\}/g, `Implement ${phaseNames} for the project`)
        .replace(/\{\{PHASE_DELIVERABLES\}\}/g, selectedPhases.map(id => `- Phase ${id}: ${phases.find(ph => ph.id === id)?.name}`).join('\n'));
      const ext = p.id === 'cursor' ? '.cursorrules' : p.id === 'copilot' ? '.md' : '.txt';
      allPrompts.push(`${'='.repeat(60)}\nFILE: ${p.id}-prompt${ext}\nPLATFORM: ${p.name}\n${'='.repeat(60)}\n\n${compiled}\n\n`);
    }
    const blob = new Blob([allPrompts.join('')], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `prompt-compiler-export-${new Date().toISOString().split('T')[0]}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const handleGenerate = async () => {
    setIsGenerating(true); setOutput('');
    const platform = platforms.find(p => p.id === selectedPlatform);
    const phaseNames = selectedPhases.map(id => phases.find(ph => ph.id === id)?.name || '').join(', ');

    const prompt = `You are a prompt engineering expert specializing in AI coding platforms. Generate an optimized, production-ready prompt for the "${platform?.name}" platform.

TARGET PLATFORM: ${platform?.name} (${platform?.desc})
TEMPLATE FORMAT: ${platform?.id}
PROJECT: ${projectId || 'Software Project'}
SELECTED PHASES: ${phaseNames} (Phases ${selectedPhases.join(', ')} of 10)

BASE TEMPLATE:
${platformTemplates[selectedPlatform] || ''}

INSTRUCTIONS:
1. Use the base template as a starting point but ENHANCE it significantly
2. Fill in all {{PLACEHOLDER}} values with detailed, actionable content
3. Add platform-specific optimizations and best practices
4. Include detailed phase instructions for each selected phase
5. Make the prompt comprehensive enough to guide the AI through full implementation
6. Add specific file structures, component lists, and API endpoints
7. Include edge cases, error handling requirements, and testing notes

Generate the COMPLETE, filled-in prompt ready for copy-paste into ${platform?.name}.`;

    try {
      const res = await fetch('/api/tools/generate', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ task: `${platform?.name} Prompt Compilation`, context: `Phases: ${phaseNames}`, systemPrompt: prompt })
      });
      if (!res.body) throw new Error('No body');
      const reader = res.body.getReader();
      const decoder = new TextDecoder();
      let done = false;
      while (!done) {
        const { value, done: d } = await reader.read();
        done = d;
        if (value) setOutput(p => p + decoder.decode(value));
      }
    } catch { setOutput('Error generating prompt. Check API keys in Settings.'); }
    finally { setIsGenerating(false); }
  };

  const activePlatform = platforms.find(p => p.id === selectedPlatform);

  return (
    <div className="h-full flex flex-col p-8 animate-in fade-in slide-in-from-bottom-4 duration-500 max-w-7xl mx-auto w-full overflow-y-auto">
      {/* Header */}
      <div className="flex flex-col md:flex-row justify-between items-start md:items-center mb-6 gap-4">
        <div className="flex items-center gap-4">
          <div className="w-12 h-12 rounded-xl bg-gradient-to-br from-purple-500/20 to-purple-500/5 border border-purple-500/30 flex items-center justify-center">
            <Layers className="w-6 h-6 text-purple-400" />
          </div>
          <div>
            <h1 className="text-2xl font-bold text-white tracking-tight">Prompt Compiler</h1>
            <p className="text-[#8b9bb4] text-sm mt-1">Stage 5 · Multi-Platform AI Prompt Generation Engine</p>
          </div>
        </div>
        <div className="flex items-center gap-3">
          <div className="flex items-center gap-2 bg-[#111622] border border-[#1e2532] rounded-lg px-3 py-1.5">
            <FolderOpen className="w-4 h-4 text-[#586c8f]" />
            <select value={projectId || ''} onChange={e => { setProjectId(e.target.value); localStorage.setItem('activeProjectId', e.target.value); }} className="bg-transparent text-sm text-white font-bold focus:outline-none">
              {projects.map(p => <option key={p.id} value={p.id}>{p.name}</option>)}
            </select>
          </div>
          <button onClick={handleExportZip} className="bg-[#111622] border border-[#1e2532] hover:border-purple-500/30 text-[#8b9bb4] hover:text-purple-400 px-4 py-2.5 rounded-lg font-bold flex items-center gap-2 transition-all text-sm">
            <Download className="w-4 h-4" /> Export All
          </button>
          <button onClick={handleGenerate} disabled={isGenerating} className="bg-purple-600 hover:bg-purple-700 text-white px-5 py-2.5 rounded-lg font-bold flex items-center gap-2 transition-all disabled:opacity-50 text-sm">
            {isGenerating ? <Loader2 className="w-4 h-4 animate-spin" /> : <Sparkles className="w-4 h-4" />}
            {isGenerating ? 'Compiling...' : 'Compile Prompt'}
          </button>
        </div>
      </div>

      {/* Stats Row */}
      <div className="grid grid-cols-2 md:grid-cols-4 gap-4 mb-6">
        <div className="bg-[#111622] border border-[#1e2532] rounded-xl p-4 text-center">
          <div className="text-3xl font-black text-white">{platforms.length}</div>
          <div className="text-[10px] uppercase tracking-widest text-[#586c8f] font-bold mt-1">Platforms</div>
        </div>
        <div className="bg-[#111622] border border-[#1e2532] rounded-xl p-4 text-center">
          <div className="text-3xl font-black text-purple-400">{selectedPhases.length}</div>
          <div className="text-[10px] uppercase tracking-widest text-[#586c8f] font-bold mt-1">Phases Selected</div>
        </div>
        <div className="bg-[#111622] border border-[#1e2532] rounded-xl p-4 text-center">
          <div className="text-3xl font-black text-green-400">{output.length > 0 ? '✓' : '—'}</div>
          <div className="text-[10px] uppercase tracking-widest text-[#586c8f] font-bold mt-1">Compiled</div>
        </div>
        <div className="bg-[#111622] border border-[#1e2532] rounded-xl p-4 text-center">
          <div className="text-3xl font-black text-blue-400">{output.split('\n').length}</div>
          <div className="text-[10px] uppercase tracking-widest text-[#586c8f] font-bold mt-1">Output Lines</div>
        </div>
      </div>

      {/* Phase Selector */}
      <div className="mb-4">
        <h3 className="text-xs font-bold text-[#586c8f] uppercase tracking-wider mb-2">Select Phases</h3>
        <div className="flex flex-wrap gap-2">
          {phases.map(ph => (
            <button key={ph.id} onClick={() => togglePhase(ph.id)} className={`px-3 py-1.5 rounded-lg text-xs font-bold transition-all flex items-center gap-1.5 ${selectedPhases.includes(ph.id) ? 'bg-purple-500/15 border border-purple-500/30 text-purple-400' : 'bg-[#111622] border border-[#1e2532] text-[#586c8f] hover:text-white'}`}>
              <span className="w-4 h-4 rounded text-[10px] font-black flex items-center justify-center bg-[#1a1b3b]">{ph.id}</span>
              {ph.name}
            </button>
          ))}
        </div>
      </div>

      {/* Main Content: Side by Side */}
      <div className="flex-1 flex gap-4 min-h-0">
        {/* Platform Cards (Left) */}
        <div className="w-72 shrink-0 overflow-y-auto space-y-2 pr-1">
          <h3 className="text-xs font-bold text-[#586c8f] uppercase tracking-wider mb-2">Target Platform</h3>
          {platforms.map(p => (
            <button key={p.id} onClick={() => setSelectedPlatform(p.id)} className={`w-full text-left p-3 rounded-xl border transition-all flex items-center gap-3 ${selectedPlatform === p.id ? `${p.bgColor} ring-1 ring-purple-500/30` : 'bg-[#111622] border-[#1e2532] hover:border-purple-500/20'}`}>
              <div className={`w-9 h-9 rounded-lg flex items-center justify-center shrink-0 ${selectedPlatform === p.id ? 'bg-[#1a1b3b]' : 'bg-[#0b0e14]'}`}>
                <p.icon className={`w-5 h-5 ${p.color}`} />
              </div>
              <div className="min-w-0">
                <div className="text-xs font-bold text-white truncate">{p.name}</div>
                <div className="text-[10px] text-[#586c8f]">{p.desc}</div>
              </div>
              {selectedPlatform === p.id && <div className="w-1.5 h-1.5 rounded-full bg-purple-400 ml-auto shrink-0" />}
            </button>
          ))}
        </div>

        {/* Output Editor (Right) */}
        <div className="flex-1 bg-[#0b0e14] border border-[#1e2532] rounded-xl overflow-hidden relative">
          <div className="absolute top-0 left-0 w-full h-9 bg-[#1a1b3b]/50 border-b border-[#1e2532] flex items-center justify-between px-4">
            <div className="flex items-center gap-2">
              {activePlatform && <activePlatform.icon className={`w-3.5 h-3.5 ${activePlatform.color}`} />}
              <span className="text-xs font-mono text-[#586c8f]">{activePlatform?.id || 'output'}-prompt.md</span>
            </div>
            <div className="flex items-center gap-2">
              {output && (
                <button onClick={handleCopy} className="flex items-center gap-1 text-[10px] font-bold text-[#586c8f] hover:text-purple-400 transition-all">
                  {copied ? <Check className="w-3 h-3 text-green-400" /> : <Copy className="w-3 h-3" />}
                  {copied ? 'Copied!' : 'Copy'}
                </button>
              )}
            </div>
          </div>
          {output ? (
            <textarea value={output} onChange={e => setOutput(e.target.value)} className="w-full h-full bg-transparent text-[#e2e8f0] font-mono text-sm p-6 pt-14 resize-none focus:outline-none" spellCheck={false} />
          ) : (
            <div className="absolute inset-0 flex flex-col items-center justify-center opacity-50 pointer-events-none">
              {isGenerating ? (
                <><Loader2 className="w-16 h-16 text-purple-400 mb-4 animate-spin" /><p className="text-[#8b9bb4] text-lg font-bold">Compiling prompt for {activePlatform?.name}...</p></>
              ) : (
                <><Layers className="w-16 h-16 text-[#586c8f] mb-4" /><p className="text-[#8b9bb4] text-lg font-bold">Select platform, phases & compile</p><p className="text-[#586c8f] text-sm mt-1">AI generates optimized prompts for each platform</p></>
              )}
            </div>
          )}
        </div>
      </div>
    </div>
  );
}
